function(noticeboard_target_link_dbus target acc)
    if(NOT NOTICEBOARD_ENABLE_DBUS)
        return()
    endif()
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(NOTICEBOARD_DBUS IMPORTED_TARGET GLOBAL dbus-1)
    if(NOT NOTICEBOARD_DBUS_FOUND)
        return()
    endif()
    target_link_libraries(${target} ${acc} PkgConfig::NOTICEBOARD_DBUS)
endfunction()
