include("${CMAKE_CURRENT_LIST_DIR}/dbus.cmake")

function(noticeboard_detect_system prefix)
    if(DEFINED NOTICEBOARD_FORCE_SYSTEM AND NOT (NOTICEBOARD_FORCE_SYSTEM STREQUAL ""))
        set(system_name ${NOTICEBOARD_FORCE_SYSTEM})
    else()
        set(system_name ${CMAKE_SYSTEM_NAME})
    endif()
    if(system_name MATCHES "^(CrayLinuxEnvironment|Linux)$")
        set(${prefix}_SYSTEM_NAME "linux" PARENT_SCOPE)
    elseif(system_name MATCHES "^(CYGWIN|MSYS|Windows)$")
        set(${prefix}_SYSTEM_NAME "windows" PARENT_SCOPE)
    elseif(system_name MATCHES "^(Darwin)$")
        set(${prefix}_SYSTEM_NAME "darwin" PARENT_SCOPE)
    else()
        set(${prefix}_SYSTEM_NAME "unknown" PARENT_SCOPE)
    endif()
    set(${prefix}_SYSTEM_NAME_REQUESTED "${system_name}")
endfunction()

function(noticeboard_target_set_system_options target acc src_dir)
    noticeboard_detect_system(NOTICEBOARD)
    if(NOTICEBOARD_SYSTEM_NAME STREQUAL "unknown")
        message(FATAL_ERROR "Unsupported system '${NOTICEBOARD_SYSTEM_NAME_REQUESTED}'")
    endif()
    cmake_language(CALL "noticeboard_target_set_${NOTICEBOARD_SYSTEM_NAME}_options" "${target}" "${acc}" "${src_dir}")
endfunction()

function(noticeboard_target_use_notify_send target acc src_dir system_name)
    if(NOTICEBOARD_ENABLE_NOTIFY_SEND)
        find_program(NOTICEBOARD_NOTIFY_SEND notify-send OPTIONAL)
        if(NOTICEBOARD_FORCE_NOTIFY_SEND OR NOT (NOTICEBOARD_NOTIFY_SEND STREQUAL NOTICEBOARD_NOTIFY_SEND-NOTFOUND))
            target_compile_definitions(${target} ${acc} NOTICEBOARD_USE_NOTIFY_SEND)
            target_sources(${target} ${acc} ${src_dir}/${system_name}/notify_send_backend.cpp)
            return()
        else()
            message(WARNING "notify-send requested but not found use NOTICEBOARD_FORCE_NOTIFY_SEND to use it anyway")
        endif()
    endif()
    target_sources(${target} ${acc} ${src_dir}/unknown/notify_send_backend.cpp)
endfunction()

function(noticeboard_target_set_linux_options target acc src_dir)
    target_compile_definitions(${target} ${acc} NOTICEBOARD_SYSTEM_LINUX)
    noticeboard_target_use_notify_send(${target} ${acc} ${src_dir} linux)
    noticeboard_target_link_dbus(${target} ${acc})
endfunction()

function(noticeboard_target_set_darwin_options target acc src_dir)
    target_compile_definitions(${target} ${acc} NOTICEBOARD_SYSTEM_DARWIN)
    message(FATAL_ERROR "Darwin is currently unsupported")
endfunction()

function(noticeboard_target_set_windows_options target acc src_dir)
    target_compile_definitions(${target} ${acc} NOTICEBOARD_SYSTEM_WINDOWS)
    message(FATAL_ERROR "Windows is currently unsupported")
endfunction()

